spring:
  application:
    name: workout-planner-api

  profiles:
    active: dev

jwt:
  secret: my-secret-key
  expiration: 86400000 # 24h in ms

app:
  security:
    token-secret: "5zFe9mcQ3O+tSB53xIxn4ZxCEThDIn1wNj3LZhipvww="
