spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workout_planner
    username: workout_user
    password: workoutpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  security:
    refresh-token-secret: ${APP_SECURITY_REFRESH_TOKEN_SECRET} 